on:
  push:
    branches:
      - master

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_3103297a_585c_414d_b92d_e94487f52976_API_KEY }}
          config_path_input: 'openfn-3103297a-585c-414d-b92d-e94487f52976-config.json'
